server:
  port: 10010


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
spring:
  application:
    name: get-way

ribbon:
##  eureka:
##    enabled: false
  ReadTimeout: 10000
  ConnectTimeout: 10000

zuul:
  routes:
    user-service:
#    /user-service/**
      path: /hello/**
#      serviceId: http://127.0.0.1:8082
#      serviceId: user-service
      serviceId: user-service
#      strip-prefix: false
  host:
      connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
      socket-timeout-millis: 60000   #socket超时