server:
  port: 10086

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#      注册到eureka上，默认为true
    register-with-eureka: false
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
#  server:
#    失效剔除时间，毫秒
#    eviction-interval-timer-in-ms: 30000
#    最小的过期时常
#    lease-expiration-duration-in-seconds: 90
#    每隔30秒向服务器发送心跳
#    lease-renewal-interval-in-seconds: 30
#    enable

# 负载均衡规则
#user-service:
#  ribbon:
#    NFLoadBalanceRuleClassName: RandomRule
spring:
  application:
    name: eureka-server-7001
